### ISSUE TITLE
Dashboard deployment.

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/CounterfactualCovid19#89]
Find a place to host a production version of the app.

**Comment by KFArnold** [comment]
@geoalison is chasing people at the university to sort financing for the page from within the project budget. Will update as I hear more.

@crangelsmith - If we wanted the page to be hosted at the Turing, do you know who would be best to speak to about this?

**Comment by crangelsmith** [comment]
@KFArnold to get the project code.

**Comment by KFArnold** [comment]
@crangelsmith Info from Alison: 

Turing code is R-LEE-001, Leeds code is RG.GEOG.116651.

**Comment by KFArnold** [comment]
Just received this update from Martin Callahan: 

"The counterfactual app is proving a little trickier (as it's three containers in concert rather than just the one) so I'll let you know when that's ready."

So they are actively working on it, and it seems like there won't be much to do on our end in terms of getting it up and running 🤞

**Comment by jemrobinson** [comment]
This is currently up and running at https://cfcovid.azurewebsites.net/ so I think we can close this issue.
